
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TCHIMOU
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        // center form
       this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jLabelClose = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldUtilisateur = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jCheckBoxShowpass = new javax.swing.JCheckBox();
        jButtonannuler = new javax.swing.JButton();
        jButtonlogin = new javax.swing.JButton();
        jLabelcreateAccount = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(439, 59));
        jPanel1.setLayout(null);

        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelClose);
        jLabelClose.setBounds(410, 10, 20, 29);

        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setText("-");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelMin);
        jLabelMin.setBounds(360, 20, 34, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CONNEXION");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 10, 170, 29);

        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 285, 34, 720);

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));
        jPanel2.setMaximumSize(new java.awt.Dimension(436, 260));
        jPanel2.setPreferredSize(new java.awt.Dimension(436, 260));
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(44, 62, 80));
        jPanel3.setMaximumSize(new java.awt.Dimension(436, 260));
        jPanel3.setPreferredSize(new java.awt.Dimension(436, 260));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Utilisateur      : ");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(20, 60, 140, 22);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Mot de passe :");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(20, 120, 140, 22);

        jTextFieldUtilisateur.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldUtilisateur.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldUtilisateur.setForeground(new java.awt.Color(204, 255, 255));
        jPanel3.add(jTextFieldUtilisateur);
        jTextFieldUtilisateur.setBounds(170, 60, 160, 30);

        jPasswordField1.setBackground(new java.awt.Color(108, 122, 137));
        jPasswordField1.setForeground(new java.awt.Color(204, 255, 255));
        jPanel3.add(jPasswordField1);
        jPasswordField1.setBounds(170, 120, 160, 30);

        jCheckBoxShowpass.setBackground(new java.awt.Color(204, 204, 255));
        jCheckBoxShowpass.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxShowpass.setText("Show pass");
        jCheckBoxShowpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxShowpassActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBoxShowpass);
        jCheckBoxShowpass.setBounds(340, 120, 90, 30);

        jButtonannuler.setBackground(new java.awt.Color(204, 0, 51));
        jButtonannuler.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonannuler.setForeground(new java.awt.Color(255, 255, 255));
        jButtonannuler.setText("Annuler");
        jButtonannuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonannulerActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonannuler);
        jButtonannuler.setBounds(90, 180, 130, 30);

        jButtonlogin.setBackground(new java.awt.Color(153, 153, 255));
        jButtonlogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonlogin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonlogin.setText("Connexion");
        jButtonlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonloginActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonlogin);
        jButtonlogin.setBounds(270, 180, 130, 30);

        jLabelcreateAccount.setForeground(new java.awt.Color(240, 240, 240));
        jLabelcreateAccount.setText("nouveau  utilisateur ? click ici pour ajouter");
        jLabelcreateAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelcreateAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelcreateAccountMouseClicked(evt);
            }
        });
        jPanel3.add(jLabelcreateAccount);
        jLabelcreateAccount.setBounds(90, 240, 240, 14);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 0, 440, 280);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
      this.setState(JFrame.ICONIFIED);// pour activer "-"
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);// pour activer "x"
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jCheckBoxShowpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxShowpassActionPerformed
       // pour voir le mot de passe
       
        if(jCheckBoxShowpass.isSelected()){
           jPasswordField1.setEchoChar((char) 0);
       }else { 
            jPasswordField1.setEchoChar('*');
       }  
          
    }//GEN-LAST:event_jCheckBoxShowpassActionPerformed

    private void jButtonannulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonannulerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonannulerActionPerformed

    private void jButtonloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonloginActionPerformed
      
        Connection con = MyConnection.getConnection();
        PreparedStatement ps ;
        ResultSet rs ;
        
        try {
            ps = con.prepareStatement("SELECT `utilisateur`, `pass`, `pic` , id FROM `user` WHERE `utilisateur` = ? AND `pass` = ?");
            ps.setString(1, jTextFieldUtilisateur.getText());
            ps.setString(2,String.valueOf(jPasswordField1.getPassword()));
            rs = ps.executeQuery();
            
            if(rs.next()){
                
                // obtenir l’ID utilisateur actuel
                Mycontacts.currentUserId = rs.getInt("id");
                System.out.println(rs.getInt("id")+ "Form Login");
                Mycontacts mcf = new  Mycontacts ();
                mcf.setVisible(true);
                mcf.pack();
                mcf.setLocationRelativeTo(null);
                mcf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                // afficher l’image du profil de l’utilisateur en haut de la page
                mcf.jLabelUserPic.setIcon(new Myfunc().resizePic(null,rs.getBytes(3), mcf.jLabelUserPic.getWidth(), mcf.jLabelUserPic.getHeight()));
                mcf.jLabelUtilisateur.setText(rs.getString(1));
                this.dispose();
                
            }else{
                JOptionPane.showMessageDialog(null, "erreur de connexion");
            }
            
                    
            
        } catch (SQLException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonloginActionPerformed

    private void jLabelcreateAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelcreateAccountMouseClicked

           signupForm supf = new  signupForm();
           supf.setVisible(true);
           supf.pack();
           supf.setLocationRelativeTo(null);
           supf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
           this.dispose();

//       Mycontacts  mcf = new  Mycontacts();
//       mcf.setVisible(true);
//       mcf.pack();
//       mcf.setLocationRelativeTo(null);
//       mcf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//       this.dispose();
    }//GEN-LAST:event_jLabelcreateAccountMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonannuler;
    private javax.swing.JButton jButtonlogin;
    private javax.swing.JCheckBox jCheckBoxShowpass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JLabel jLabelcreateAccount;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextFieldUtilisateur;
    // End of variables declaration//GEN-END:variables
}
