
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TCHIMOU
 */
public class Mycontacts extends javax.swing.JFrame {

    /**
     * Creates new form Mycontacts
     */
    
    String imagePth = null ;
    public static int currentUserId;
    int pos = 0;
    public Mycontacts() {
        initComponents();
        populateJtable();
        // pour faire resortir les traits ou ligne du tableau
        jTable1.setShowGrid(true);
        // pour donner de la couleur aux traits ou lignes du tableau
        jTable1.setGridColor(Color.BLACK);
        jTable1.setBackground(Color.lightGray);
        jTable1.setSelectionBackground(Color.GRAY);
        JTableHeader th = jTable1.getTableHeader();
        th.setForeground(Color.darkGray);
        th.setFont(new Font("Tahoma",Font.PLAIN,14));
        System.out.println(currentUserId + "Form Contact");
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // 
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelClose = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelUserPic = new javax.swing.JLabel();
        jLabelUtilisateur = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldemail = new javax.swing.JTextField();
        jTextFieldId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldtel1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldtel2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxmention = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabelcontactImage = new javax.swing.JLabel();
        jButtonBrowse = new javax.swing.JButton();
        jButtonSupprimercontact = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonAjoutercontact = new javax.swing.JButton();
        jTextFieldnom = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButtonModifiercontact = new javax.swing.JButton();
        jButtonLast = new javax.swing.JButton();
        jButtonFirst = new javax.swing.JButton();
        jButtonNext = new javax.swing.JButton();
        jButtonPrevious = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(0, 0, 102));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(439, 59));
        jPanel1.setLayout(null);

        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelClose);
        jLabelClose.setBounds(880, 10, 20, 29);

        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setText("-");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelMin);
        jLabelMin.setBounds(810, 20, 34, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mon Repertoire");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(270, 10, 200, 29);

        jLabelUserPic.setForeground(new java.awt.Color(0, 51, 153));
        jLabelUserPic.setMaximumSize(new java.awt.Dimension(50, 50));
        jLabelUserPic.setMinimumSize(new java.awt.Dimension(50, 50));
        jLabelUserPic.setOpaque(true);
        jPanel1.add(jLabelUserPic);
        jLabelUserPic.setBounds(0, 0, 50, 50);

        jLabelUtilisateur.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelUtilisateur.setForeground(new java.awt.Color(51, 0, 51));
        jLabelUtilisateur.setText("Utilisateur");
        jPanel1.add(jLabelUtilisateur);
        jLabelUtilisateur.setBounds(70, 20, 80, 17);

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));
        jPanel2.setMaximumSize(new java.awt.Dimension(436, 260));
        jPanel2.setPreferredSize(new java.awt.Dimension(436, 260));

        jPanel3.setBackground(new java.awt.Color(44, 62, 80));
        jPanel3.setMaximumSize(new java.awt.Dimension(436, 260));
        jPanel3.setPreferredSize(new java.awt.Dimension(436, 260));
        jPanel3.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Id               :");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(20, 50, 110, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Mention    :");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(20, 320, 140, 22);

        jTextFieldemail.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldemail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldemail.setForeground(new java.awt.Color(204, 255, 255));
        jPanel3.add(jTextFieldemail);
        jTextFieldemail.setBounds(180, 270, 180, 30);

        jTextFieldId.setEditable(false);
        jTextFieldId.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldId.setForeground(new java.awt.Color(204, 255, 255));
        jPanel3.add(jTextFieldId);
        jTextFieldId.setBounds(180, 50, 180, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Numéro 1 :");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(20, 150, 140, 22);

        jTextFieldtel1.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldtel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldtel1.setForeground(new java.awt.Color(204, 255, 255));
        jPanel3.add(jTextFieldtel1);
        jTextFieldtel1.setBounds(180, 150, 180, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Numéro 2 :");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(20, 210, 140, 22);

        jTextFieldtel2.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldtel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldtel2.setForeground(new java.awt.Color(204, 255, 255));
        jPanel3.add(jTextFieldtel2);
        jTextFieldtel2.setBounds(180, 210, 180, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Photo de profil :");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(420, 50, 150, 22);

        jComboBoxmention.setBackground(new java.awt.Color(102, 153, 255));
        jComboBoxmention.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Famille", "Amis", "work" }));
        jComboBoxmention.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxmentionActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBoxmention);
        jComboBoxmention.setBounds(180, 320, 180, 30);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator1);
        jSeparator1.setBounds(400, 40, 10, 260);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("Email         :");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(20, 270, 140, 22);

        jLabelcontactImage.setBackground(new java.awt.Color(108, 122, 137));
        jLabelcontactImage.setOpaque(true);
        jPanel3.add(jLabelcontactImage);
        jLabelcontactImage.setBounds(580, 50, 180, 160);

        jButtonBrowse.setBackground(new java.awt.Color(204, 0, 51));
        jButtonBrowse.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonBrowse.setText("Feuilleter");
        jButtonBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowseActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonBrowse);
        jButtonBrowse.setBounds(780, 100, 85, 23);

        jButtonSupprimercontact.setBackground(new java.awt.Color(204, 0, 51));
        jButtonSupprimercontact.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonSupprimercontact.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSupprimercontact.setText("Supprimer");
        jButtonSupprimercontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprimercontactActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonSupprimercontact);
        jButtonSupprimercontact.setBounds(450, 320, 130, 31);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(20, 400, 960, 300);

        jButtonAjoutercontact.setBackground(new java.awt.Color(153, 153, 255));
        jButtonAjoutercontact.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonAjoutercontact.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAjoutercontact.setText("Ajouter");
        jButtonAjoutercontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjoutercontactActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonAjoutercontact);
        jButtonAjoutercontact.setBounds(770, 320, 111, 31);

        jTextFieldnom.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldnom.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldnom.setForeground(new java.awt.Color(204, 255, 255));
        jPanel3.add(jTextFieldnom);
        jTextFieldnom.setBounds(180, 100, 180, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        jLabel12.setText("Nom           :");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(20, 100, 110, 22);

        jButtonModifiercontact.setBackground(new java.awt.Color(153, 153, 255));
        jButtonModifiercontact.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonModifiercontact.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModifiercontact.setText("Modifier");
        jButtonModifiercontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifiercontactActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonModifiercontact);
        jButtonModifiercontact.setBounds(600, 320, 130, 31);

        jButtonLast.setBackground(new java.awt.Color(204, 0, 51));
        jButtonLast.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonLast.setText(">>");
        jButtonLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLastActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonLast);
        jButtonLast.setBounds(350, 370, 50, 23);

        jButtonFirst.setBackground(new java.awt.Color(204, 0, 51));
        jButtonFirst.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonFirst.setText("<<");
        jButtonFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFirstActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonFirst);
        jButtonFirst.setBounds(100, 370, 50, 23);

        jButtonNext.setBackground(new java.awt.Color(153, 153, 255));
        jButtonNext.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonNext.setText("<");
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonNext);
        jButtonNext.setBounds(180, 370, 50, 23);

        jButtonPrevious.setBackground(new java.awt.Color(153, 153, 255));
        jButtonPrevious.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonPrevious.setText(">");
        jButtonPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreviousActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonPrevious);
        jButtonPrevious.setBounds(260, 370, 50, 23);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 985, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 985, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void populateJtable() {
        
        contactQuery cq = new contactQuery();
        ArrayList<Contact> ctList = cq.contactList(currentUserId);
        // `tel1`, `tel2`, `email`, `mention`, `pic`
        String[] colNames = {"Id","Nom","Numero 1","Numero2","Email","Mention","Image"};
        Object[][] rows = new Object[ctList.size()][7];
        
        for(int i = 0;i < ctList.size();i++){
            rows[i][0] = ctList.get(i).getCid();
            rows[i][1] = ctList.get(i).getnom();
            rows[i][2] = ctList.get(i).gettel1();
            rows[i][3] = ctList.get(i).gettel2();
            rows[i][4] = ctList.get(i).getemail();
            rows[i][5] = ctList.get(i).getmention();
            
            ImageIcon pic = new ImageIcon(new ImageIcon
                                         (ctList.get(i).getpic())
                                         .getImage()
                                         .getScaledInstance(120,80,Image.SCALE_SMOOTH));
            rows[i][6] = pic;
            
        }
        
        MyModel mmd = new MyModel(rows,colNames);
        jTable1.setModel(mmd);
        jTable1.setRowHeight(80);
        jTable1.getColumnModel().getColumn(6).setPreferredWidth(120);
        
    }
    
    
    
    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);// pour activer "x"
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        this.setState(JFrame.ICONIFIED);// pour activer "-"
    }//GEN-LAST:event_jLabelMinMouseClicked
// ok 
    private void jButtonBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowseActionPerformed
       
           Myfunc mf = new Myfunc();
           imagePth = mf.browseImage(jLabelcontactImage);
           System.out.println(imagePth);

    }//GEN-LAST:event_jButtonBrowseActionPerformed

    private void showData(int index){
        
        jTextFieldnom.setText(jTable1.getValueAt(index,1).toString());
        
         // group phone email pic
          
        jTextFieldtel1.setText(jTable1.getValueAt(index,2).toString());
        jTextFieldtel2.setText(jTable1.getValueAt(index,3).toString());
        jTextFieldemail.setText(jTable1.getValueAt(index,4).toString());
        jComboBoxmention.setSelectedItem(jTable1.getValueAt(index,5));
        jTextFieldId.setText(jTable1.getValueAt(index,0).toString());
        Image pic = ((ImageIcon)jTable1.getValueAt(index, 6)).getImage().getScaledInstance(jLabelcontactImage.getWidth(),jLabelcontactImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon img = new ImageIcon(pic);
        
        jLabelcontactImage.setIcon(img);
    }
    
    private void jButtonSupprimercontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprimercontactActionPerformed
        // l’utilisateur doit sélectionner un contact à modifier
        if(!jTextFieldId.getText().equals("")){
            int id = Integer.valueOf(jTextFieldId.getText());
            contactQuery cq = new contactQuery();
            cq.deleteContact(id);
            refreshJtable();
            clearFields();
        }else{
            
            JOptionPane.showMessageDialog(null,"vous devez selection contact");
        
        }
            
            
        
      
       
       
        
       
    }//GEN-LAST:event_jButtonSupprimercontactActionPerformed

    private void jComboBoxmentionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxmentionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxmentionActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        // display selected Jtable row data
        // get selected row index 
        int rowIndex = jTable1.getSelectedRow();
        jTextFieldnom.setText(jTable1.getValueAt(rowIndex,1).toString());
        
         // group phone email email pic
          
        jTextFieldtel1.setText(jTable1.getValueAt(rowIndex,2).toString());
        jTextFieldtel2.setText(jTable1.getValueAt(rowIndex,3).toString());
        jTextFieldemail.setText(jTable1.getValueAt(rowIndex,4).toString());
        jComboBoxmention.setSelectedItem(jTable1.getValueAt(rowIndex,5));
        jTextFieldId.setText(jTable1.getValueAt(rowIndex,0).toString());
        Image pic = ((ImageIcon)jTable1.getValueAt(rowIndex, 6)).getImage().getScaledInstance(jLabelcontactImage.getWidth(),jLabelcontactImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon img = new ImageIcon(pic);
        
        jLabelcontactImage.setIcon(img);
        
        
        
        
       
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonAjoutercontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjoutercontactActionPerformed
      
      
      String nom = jTextFieldnom.getText();
      String tel1 = jTextFieldtel1.getText();
      String tel2 = jTextFieldtel2.getText();
      String email = jTextFieldemail.getText();
      String mention = jComboBoxmention.getSelectedItem().toString();
      // vous pouvez vérifier si tous les champs sont vides
      // mais dans ce cas je vérifierai seulement si l’utilisateur sélectionne une image
      // et pour ce faire, nous allons utiliser imagepath 
      
      byte[] img = null;
      
      if(imagePth != null){
      try{
          Path pth = Paths.get(imagePth);
          img = Files.readAllBytes(pth); 
          Contact c = new Contact(null,nom,tel1,tel2,email,mention,img,currentUserId);
          contactQuery cq = new contactQuery();
          cq.insertContact(c);
          refreshJtable();
          clearFields();
      } catch(IOException ex) {
          Logger.getLogger(Mycontacts.class.getName()).log(Level.SEVERE,null,ex);
          }  
      }  else{
          
          JOptionPane.showMessageDialog(null,"vous devez selection une photo de profile");
      }
      
      
        
    
    }//GEN-LAST:event_jButtonAjoutercontactActionPerformed
// pour actualiser
    public void clearFields(){
        
        jTextFieldId.setText("") ;
        jTextFieldtel1.setText("") ;
        jTextFieldtel2.setText("") ;
        jTextFieldemail.setText("") ;
        jComboBoxmention.setSelectedIndex(0);
        jLabelcontactImage.setIcon(null);
        // définir imagePth à null pour empêcher l’utilisateur d’ajouter des images dupliquées indésirables
        imagePth = null;
        
    }
    
     public void refreshJtable(){
        
       jTable1.setModel(new DefaultTableModel()) ;
        populateJtable();
    }
    
    
    
    private void jButtonModifiercontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifiercontactActionPerformed
      // l’utilisateur doit sélectionner un contact à supprimer
      if(!jTextFieldId.getText().equals("")) {
     
      int id =  Integer.valueOf(jTextFieldId.getText());
      String nom = jTextFieldnom.getText();
      String tel1 = jTextFieldtel1.getText();
      String tel2 = jTextFieldtel2.getText();
      String email = jTextFieldemail.getText();
      String mention = jComboBoxmention.getSelectedItem().toString();
      // si l’utilisateur souhaite mettre à jour les données et l’image
      if(imagePth !=null){
          
        byte[] img = null;
        try{
            Path pth = Paths.get(imagePth);
            img = Files.readAllBytes(pth);
            
            Contact c = new Contact(id,nom,tel1,tel2,email,mention,img,currentUserId);
            contactQuery cq = new contactQuery();
            cq.updateContact(c,true);
            refreshJtable();
            clearFields();
        } 
        catch(FileNotFoundException ex) {
            Logger.getLogger(Mycontacts.class.getName()).log(Level.SEVERE,null,ex);
          
        } 
        catch(IOException ex) {
            Logger.getLogger(Mycontacts.class.getName()).log(Level.SEVERE,null,ex);
          
      } 
      } else{
            Contact c = new Contact(id,nom,tel1,tel2,email,mention,null,currentUserId);
            contactQuery cq = new contactQuery();
            cq.updateContact(c,false);
            refreshJtable();
            clearFields();
      
      }
      }else{
          JOptionPane.showMessageDialog(null,"vous devez selection contact");
      
      }
      
      
      
     
      
      
     
    }//GEN-LAST:event_jButtonModifiercontactActionPerformed

    private void jButtonLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLastActionPerformed
       pos = jTable1.getRowCount()- 1;
       showData(pos);

    }//GEN-LAST:event_jButtonLastActionPerformed

    private void jButtonFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFirstActionPerformed
        pos = jTable1.getRowCount()- 1;
        showData(0);
    }//GEN-LAST:event_jButtonFirstActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void jButtonPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreviousActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPreviousActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mycontacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mycontacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mycontacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mycontacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mycontacts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjoutercontact;
    private javax.swing.JButton jButtonBrowse;
    private javax.swing.JButton jButtonFirst;
    private javax.swing.JButton jButtonLast;
    private javax.swing.JButton jButtonModifiercontact;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonPrevious;
    private javax.swing.JButton jButtonSupprimercontact;
    private javax.swing.JComboBox<String> jComboBoxmention;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMin;
    public javax.swing.JLabel jLabelUserPic;
    public javax.swing.JLabel jLabelUtilisateur;
    private javax.swing.JLabel jLabelcontactImage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldemail;
    private javax.swing.JTextField jTextFieldnom;
    private javax.swing.JTextField jTextFieldtel1;
    private javax.swing.JTextField jTextFieldtel2;
    // End of variables declaration//GEN-END:variables
}
