
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author TCHIMOU
 */
public class signupForm extends javax.swing.JFrame {

    /**
     * Creates new form signupForm
     */
    String imagePth = null ;
    public signupForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldUtilisateur = new javax.swing.JTextField();
        jPasswordFieldRmotdepasse = new javax.swing.JPasswordField();
        jButtonannuler = new javax.swing.JButton();
        jButtonEnregistrer = new javax.swing.JButton();
        jLabelcreateAccount = new javax.swing.JLabel();
        jTextFieldNom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPasswordFieldMotdepasse = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelImage = new javax.swing.JLabel();
        jButtonBrowse = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelClose = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(44, 62, 80));
        jPanel3.setMaximumSize(new java.awt.Dimension(436, 260));
        jPanel3.setPreferredSize(new java.awt.Dimension(436, 260));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Utilisateur      : ");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(20, 110, 140, 22);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Image :");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(120, 330, 80, 22);

        jTextFieldUtilisateur.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldUtilisateur.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldUtilisateur.setForeground(new java.awt.Color(204, 255, 255));
        jPanel3.add(jTextFieldUtilisateur);
        jTextFieldUtilisateur.setBounds(190, 110, 160, 30);

        jPasswordFieldRmotdepasse.setBackground(new java.awt.Color(108, 122, 137));
        jPasswordFieldRmotdepasse.setForeground(new java.awt.Color(204, 255, 255));
        jPanel3.add(jPasswordFieldRmotdepasse);
        jPasswordFieldRmotdepasse.setBounds(190, 250, 160, 30);

        jButtonannuler.setBackground(new java.awt.Color(204, 0, 51));
        jButtonannuler.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonannuler.setForeground(new java.awt.Color(255, 255, 255));
        jButtonannuler.setText("Annuler");
        jButtonannuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonannulerActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonannuler);
        jButtonannuler.setBounds(70, 527, 130, 30);

        jButtonEnregistrer.setBackground(new java.awt.Color(153, 153, 255));
        jButtonEnregistrer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonEnregistrer.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEnregistrer.setText("Enregister");
        jButtonEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnregistrerActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonEnregistrer);
        jButtonEnregistrer.setBounds(336, 527, 130, 30);

        jLabelcreateAccount.setForeground(new java.awt.Color(240, 240, 240));
        jLabelcreateAccount.setText("Si vous avez déja un compte ? click ici pour vous identifier");
        jLabelcreateAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelcreateAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelcreateAccountMouseClicked(evt);
            }
        });
        jPanel3.add(jLabelcreateAccount);
        jLabelcreateAccount.setBounds(117, 605, 275, 14);

        jTextFieldNom.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldNom.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldNom.setForeground(new java.awt.Color(204, 255, 255));
        jPanel3.add(jTextFieldNom);
        jTextFieldNom.setBounds(190, 60, 160, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Nom                :");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(20, 60, 140, 22);

        jPasswordFieldMotdepasse.setBackground(new java.awt.Color(108, 122, 137));
        jPasswordFieldMotdepasse.setForeground(new java.awt.Color(204, 255, 255));
        jPanel3.add(jPasswordFieldMotdepasse);
        jPasswordFieldMotdepasse.setBounds(190, 190, 160, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Mot de passe :");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(20, 190, 140, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Mot de passe :");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(20, 250, 140, 22);

        jLabelImage.setBackground(new java.awt.Color(108, 122, 137));
        jLabelImage.setOpaque(true);
        jPanel3.add(jLabelImage);
        jLabelImage.setBounds(206, 330, 160, 139);

        jButtonBrowse.setBackground(new java.awt.Color(204, 0, 51));
        jButtonBrowse.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonBrowse.setText("Feuilleter");
        jButtonBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowseActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonBrowse);
        jButtonBrowse.setBounds(376, 330, 90, 23);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(439, 59));
        jPanel1.setLayout(null);

        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelClose);
        jLabelClose.setBounds(508, 17, 20, 29);

        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setText("-");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelMin);
        jLabelMin.setBounds(464, 20, 34, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CONNEXION");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 10, 170, 29);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonannulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonannulerActionPerformed
       
        System.exit(0);
        
    }//GEN-LAST:event_jButtonannulerActionPerformed
 
    public boolean verifData(){
        // utilisateur  - nom - mot de passe are empty
        if(jTextFieldNom.getText().equals("") && jTextFieldNom.getText().equals("") 
                || jTextFieldUtilisateur.getText().equals("") 
                || String.valueOf(jPasswordFieldMotdepasse.getPassword()).equals("")){
            
            JOptionPane.showMessageDialog(null,"one or More Field are empty");
            return false ;
        
        }
        
        // if pass1 are different from pass2 
        else if( !String.valueOf(jPasswordFieldMotdepasse.getPassword()).equals(String.valueOf(jPasswordFieldRmotdepasse.getPassword()))){ 
           
            JOptionPane.showMessageDialog(null,"Mot de Passe Incorrect ");
            return false ;
        } 
        
        // if no image was select 
        else if(imagePth == null ){
            
            JOptionPane.showMessageDialog(null,"Pas d'image selectionée");
            return false ;
        }
         // else everything is ok
        else{
            
            return true ;
        
        }

    
            
            }
    
     
    private void jButtonEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnregistrerActionPerformed
       // connection à la Bd
       
        if ( verifData()){
            
             Connection con = MyConnection.getConnection();
             PreparedStatement ps ;
        
        try {
                    ps = con.prepareStatement("INSERT INTO `user`( `Nom`, `utilisateur`, `pass`, `pic`) VALUES (?,?,?,?)");
                    ps.setString(1, jTextFieldNom.getText());
                    ps.setString(2, jTextFieldUtilisateur.getText());
                    ps.setString(3,String.valueOf(jPasswordFieldMotdepasse.getPassword()));
                    
                    InputStream img = new FileInputStream(new File(imagePth));
                    ps.setBlob(4,img);
                    // pour l'utilisateur
                    if(isUtilisateurExiste( jTextFieldUtilisateur.getText())){
                    
                       JOptionPane.showMessageDialog(null, "le nom de l'urilisateur existe déja");
                    }
                    if(ps.executeUpdate()!= 0){
                        
                        JOptionPane.showMessageDialog(null, "Account Created");
                        
                    }else{
                        JOptionPane.showMessageDialog(null, "Somthing wrong");
                    }
                    
                    } catch (Exception ex) {
            Logger.getLogger(signupForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
            
        
        
        
        
        
    }//GEN-LAST:event_jButtonEnregistrerActionPerformed

    private void jLabelcreateAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelcreateAccountMouseClicked
        LoginForm Logf = new LoginForm ();
        Logf.setVisible(true);
        Logf.pack();
        Logf.setLocationRelativeTo(null);
        Logf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelcreateAccountMouseClicked

    // pour signaler lorsque l'utilisateur exixte déja
    public boolean isUtilisateurExiste(String un){
        
        boolean uExist = false ;
        Connection con = MyConnection.getConnection();
        PreparedStatement ps ;
        ResultSet rs ;
        
        try {
            ps = con.prepareStatement("SELECT * FROM `user` WHERE `utilisateur` = ?");
            ps.setString(1, jTextFieldUtilisateur.getText());
            
            rs = ps.executeQuery();
            
            if(rs.next()){
                uExist = true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return uExist;
}
    
    
    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);// pour activer "x"
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        this.setState(JFrame.ICONIFIED);// pour activer "-"
    }//GEN-LAST:event_jLabelMinMouseClicked

//    // pour régler la taille de l'image
//    public ImageIcon resizePic(String picPath){
//        
//        ImageIcon myImg = new ImageIcon(picPath);
//        Image img = myImg.getImage().getScaledInstance(jLabelImage.getWidth(), jLabelImage.getHeight(), Image.SCALE_SMOOTH);
//        ImageIcon myPicture = new ImageIcon(img);
//        return myPicture;
//    }
    
    private void jButtonBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowseActionPerformed
       
           Myfunc mf = new Myfunc();
           imagePth = mf.browseImage(jLabelImage);
      
    }//GEN-LAST:event_jButtonBrowseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signupForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBrowse;
    private javax.swing.JButton jButtonEnregistrer;
    private javax.swing.JButton jButtonannuler;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JLabel jLabelcreateAccount;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordFieldMotdepasse;
    private javax.swing.JPasswordField jPasswordFieldRmotdepasse;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldUtilisateur;
    // End of variables declaration//GEN-END:variables
}
